services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wedding_backend
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-key-12345}
      PORT: 3000
      NODE_ENV: development
      TZ: Asia/Jakarta
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - /home/upload:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wedding_frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped
