services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: wedding_backend_prod
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      NODE_ENV: production
      TZ: ${TZ:-Asia/Jakarta}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    volumes:
      - /home/upload:/app/uploads
    restart: unless-stopped
    networks:
      - wedding_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: wedding_frontend_prod
    ports:
      - "5173:3000"
    restart: unless-stopped
    networks:
      - wedding_network

networks:
  wedding_network:
    driver: bridge
